language: node_js
node_js:
  - 7
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NOTE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm start &
  - sleep 5
  # - npm run test